### GET QUESTIONS



GET  http://127.0.0.1:5001/api/questions
Content-Type: application/json





### DELETE QUESTIONS

DELETE http://127.0.0.1:5001/api/questions/67667e4e25f995a5ebb1606b
Content-Type: application/json

### SUBMIT QUESTIONS

POST http://127.0.0.1:5001/api/questions
Content-Type: application/json

{
    "name":"Mark", "question":"Some other questions"
    }