### GET QUESTIONS



GET  http://127.0.0.1:5001/api/questions
Content-Type: application/json





### DELETE QUESTIONS

DELETE http://127.0.0.1:5001/api/questions/676686be827cdba62a20f140
Content-Type: application/json

### SUBMIT QUESTIONS

POST http://127.0.0.1:5001/api/questions
Content-Type: application/json

{
    "name":"Mark", 
    "content":"Some other questions",
    "link":"SomeRandomLink"
    }


### UPDATE QUESTIONS